import keyMirror from "keymirror";

import type {
  ChainExplorerRef,
  ChainProps,
  ChainRpcRef,
  CurrencyRef,
  LanguageRef,
} from "~utils/interfaces";

export enum ChainKey {
  ARBITRUM = "Arbitrum",
  AVALANCHE = "Avalanche",
  BASE = "Base",
  BITCOIN = "Bitcoin",
  BITCOINCASH = "BitcoinCash",
  BLAST = "Blast",
  BSCCHAIN = "BSC",
  CRONOSCHAIN = "CronosChain",
  DASH = "Dash",
  DOGECOIN = "Dogecoin",
  DYDX = "Dydx",
  ETHEREUM = "Ethereum",
  GAIACHAIN = "Cosmos",
  KUJIRA = "Kujira",
  LITECOIN = "Litecoin",
  MAYACHAIN = "MayaChain",
  OPTIMISM = "Optimism",
  POLKADOT = "Polkadot",
  POLYGON = "Polygon",
  SOLANA = "Solana",
  SUI = "Sui",
  THORCHAIN = "THORChain",
  ZKSYNC = "Zksync",
}

export enum Currency {
  AUD = "AUD",
  CAD = "CAD",
  CNY = "CNY",
  EUR = "EUR",
  GBP = "GBP",
  JPY = "JPY",
  RUB = "RUB",
  SEK = "SEK",
  SGD = "SGD",
  USD = "USD",
}

export enum Language {
  CROATIA = "hr",
  DUTCH = "nl",
  ENGLISH = "en",
  GERMAN = "de",
  ITALIAN = "it",
  RUSSIAN = "ru",
  PORTUGUESE = "pt",
  SPANISH = "es",
}

export const storageKey = keyMirror({
  CURRENCY: true,
  LANGUAGE: true,
  VAULTS: true,
});

export const errorKey = keyMirror({
  FAIL_TO_GET_ACCOUNTS: true,
  FAIL_TO_GET_ADDRESS: true,
  FAIL_TO_GET_VAULT: true,
  FAIL_TO_GET_VAULTS: true,
  FAIL_TO_GET_TRANSACTION: true,
  FAIL_TO_INIT_WASM: true,
  INVALID_CHAIN: true,
  INVALID_EXTENSION: true,
  INVALID_FILE: true,
  INVALID_QRCODE: true,
  INVALID_VAULT: true,
});

export const currencyName: CurrencyRef = {
  [Currency.AUD]: "Australian Dollar",
  [Currency.CAD]: "Canadian Dollar",
  [Currency.CNY]: "Chinese Yuan",
  [Currency.EUR]: "European Euro",
  [Currency.GBP]: "British Pound",
  [Currency.JPY]: "Japanese Yen",
  [Currency.RUB]: "Russian Ruble",
  [Currency.SEK]: "Swedish Krona",
  [Currency.SGD]: "Singapore Dollar",
  [Currency.USD]: "United States Dollar",
};

export const currencySymbol: CurrencyRef = {
  [Currency.AUD]: "A$",
  [Currency.CAD]: "C$",
  [Currency.CNY]: "¥",
  [Currency.EUR]: "€",
  [Currency.GBP]: "£",
  [Currency.JPY]: "¥",
  [Currency.RUB]: "₽",
  [Currency.SEK]: "kr",
  [Currency.SGD]: "S$",
  [Currency.USD]: "$",
};

export const languageName: LanguageRef = {
  [Language.CROATIA]: "Hrvatski",
  [Language.DUTCH]: "Dutch",
  [Language.ENGLISH]: "English",
  [Language.GERMAN]: "Deutsch",
  [Language.ITALIAN]: "Italiano",
  [Language.PORTUGUESE]: "Português",
  [Language.RUSSIAN]: "Русский",
  [Language.SPANISH]: "Espanol",
};

export const explorerUrl: ChainExplorerRef = {
  [ChainKey.ARBITRUM]: "https://arbiscan.io",
  [ChainKey.AVALANCHE]: "https://snowtrace.io",
  [ChainKey.BASE]: "https://basescan.org",
  [ChainKey.BITCOIN]: "https://blockchair.com/bitcoin",
  [ChainKey.BITCOINCASH]: "https://blockchair.com/bitcoin-cash",
  [ChainKey.BLAST]: "https://blastscan.io",
  [ChainKey.BSCCHAIN]: "https://bscscan.com",
  [ChainKey.CRONOSCHAIN]: "https://cronoscan.com",
  [ChainKey.DASH]: "https://blockchair.com/dash",
  [ChainKey.DOGECOIN]: "https://blockchair.com/dogecoin",
  [ChainKey.DYDX]: "https://www.mintscan.io/dydx",
  [ChainKey.ETHEREUM]: "https://etherscan.io",
  [ChainKey.GAIACHAIN]: "https://www.mintscan.io/cosmos",
  [ChainKey.KUJIRA]: "https://finder.kujira.network",
  [ChainKey.LITECOIN]: "https://blockchair.com/litecoin",
  [ChainKey.MAYACHAIN]: "https://www.mayascan.org",
  [ChainKey.OPTIMISM]: "https://optimistic.etherscan.io",
  [ChainKey.POLKADOT]: "https://polkadot.subscan.io/account",
  [ChainKey.POLYGON]: "https://polygonscan.com",
  [ChainKey.SOLANA]: "https://explorer.solana.com",
  [ChainKey.THORCHAIN]: "https://thorchain.net/tx",
  [ChainKey.ZKSYNC]: "https://explorer.zksync.io",
};

export const rpcUrl: ChainRpcRef = {
  [ChainKey.ARBITRUM]: "https://arbitrum-one-rpc.publicnode.com",
  [ChainKey.AVALANCHE]: "https://avalanche-c-chain-rpc.publicnode.com",
  [ChainKey.BASE]: "https://base-rpc.publicnode.com",
  [ChainKey.BLAST]: "https://rpc.ankr.com/blast",
  [ChainKey.BSCCHAIN]: "https://bsc-rpc.publicnode.com",
  [ChainKey.CRONOSCHAIN]: "https://cronos-evm-rpc.publicnode.com",
  [ChainKey.OPTIMISM]: "https://optimism-rpc.publicnode.com",
  [ChainKey.ETHEREUM]: "https://ethereum-rpc.publicnode.com",
  [ChainKey.POLYGON]: "https://polygon-bor-rpc.publicnode.com",
  [ChainKey.ZKSYNC]: "https://mainnet.era.zksync.io",
};

export const chains: ChainProps[] = [
  {
    cmcId: 1027,
    decimals: 18,
    id: "0xa4b1",
    name: ChainKey.ARBITRUM,
    ticker: "ETH",
  },
  {
    cmcId: 5805,
    decimals: 18,
    id: "0xa86a",
    name: ChainKey.AVALANCHE,
    ticker: "AVAX",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "0x2105",
    name: ChainKey.BASE,
    ticker: "ETH",
  },
  {
    cmcId: 1,
    decimals: 8,
    id: "0x1f96",
    name: ChainKey.BITCOIN,
    ticker: "BTC",
  },
  {
    cmcId: 1831,
    decimals: 8,
    id: "0x2710",
    name: ChainKey.BITCOINCASH,
    ticker: "BCH",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "0x13e31",
    name: ChainKey.BLAST,
    ticker: "ETH",
  },
  {
    cmcId: 1839,
    decimals: 18,
    id: "0x38",
    name: ChainKey.BSCCHAIN,
    ticker: "BNB",
  },
  {
    cmcId: 3635,
    decimals: 18,
    id: "0x19",
    name: ChainKey.CRONOSCHAIN,
    ticker: "CRO",
  },
  {
    cmcId: 74,
    decimals: 8,
    id: "0x7d0",
    name: ChainKey.DOGECOIN,
    ticker: "DOGE",
  },
  {
    cmcId: 28324,
    decimals: 18,
    id: "",
    name: ChainKey.DYDX,
    ticker: "DYDX",
  },
  {
    cmcId: 131,
    decimals: 8,
    id: "",
    name: ChainKey.DASH,
    ticker: "DASH",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "0x1",
    name: ChainKey.ETHEREUM,
    ticker: "ETH",
  },
  {
    cmcId: 3794,
    decimals: 6,
    id: "",
    name: ChainKey.GAIACHAIN,
    ticker: "ATOM",
  },
  {
    cmcId: 15185,
    decimals: 6,
    id: "",
    name: ChainKey.KUJIRA,
    ticker: "KUJI",
  },
  {
    cmcId: 2,
    decimals: 8,
    id: "",
    name: ChainKey.LITECOIN,
    ticker: "LTC",
  },
  {
    cmcId: 23534,
    decimals: 10,
    id: "",
    name: ChainKey.MAYACHAIN,
    ticker: "CACAO",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "",
    name: ChainKey.OPTIMISM,
    ticker: "ETH",
  },
  {
    cmcId: 6636,
    decimals: 10,
    id: "",
    name: ChainKey.POLKADOT,
    ticker: "DOT",
  },
  {
    cmcId: 3890,
    decimals: 18,
    id: "0x89",
    name: ChainKey.POLYGON,
    ticker: "MATIC",
  },
  {
    cmcId: 5426,
    decimals: 9,
    id: "",
    name: ChainKey.SOLANA,
    ticker: "SOL",
  },
  {
    cmcId: 4157,
    decimals: 8,
    id: "",
    name: ChainKey.THORCHAIN,
    ticker: "RUNE",
  },
];

export const supportedChains: ChainProps[] = [
  {
    cmcId: 1027,
    decimals: 18,
    id: "0xa4b1",
    name: ChainKey.ARBITRUM,
    ticker: "ETH",
  },
  {
    cmcId: 5805,
    decimals: 18,
    id: "0xa86a",
    name: ChainKey.AVALANCHE,
    ticker: "AVAX",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "0x2105",
    name: ChainKey.BASE,
    ticker: "ETH",
  },
  {
    cmcId: 1839,
    decimals: 18,
    id: "0x38",
    name: ChainKey.BSCCHAIN,
    ticker: "BNB",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "0x1",
    name: ChainKey.ETHEREUM,
    ticker: "ETH",
  },
  {
    cmcId: 1027,
    decimals: 18,
    id: "",
    name: ChainKey.OPTIMISM,
    ticker: "ETH",
  },
];