import keyMirror from "keymirror";

export default keyMirror({
  // A
  ACTIVE: true,
  ADD_NEW_VAULT: true,
  ADD_VAULT_QRCODE: true,
  // B
  // C
  CHOOSE_VAULT: true,
  CONNECTED_DAPPS: true,
  CURRENCY: true,
  // D
  DELETE_VAULT: true,
  DROP_FILE_HERE: true,
  DROP_FILE_HERE_OR: true,
  // E
  // F
  FAQ: true,
  FIND_YOUR_QRCODE: true,
  // G
  // H
  // I
  IMPORT_FAILED: true,
  IMPORT_SUCCESSED: true,
  IMPORT_VAULT: true,
  // J
  // K
  // L
  LANGUAGE: true,
  // M
  // N
  NAME: true,
  // O
  OTHER: true,
  OTHER_VAULTS: true,
  // P
  // Q
  // R
  RENAME_VAULT: true,
  // S
  SAVE: true,
  START: true,
  SETTINGS: true,
  // U
  UNLINK: true,
  UPLOAD_IT: true,
  // V
  VAULT_SETTINGS: true,
  VULT_TOKEN: true,
  VULTISIG: true,
  VULTISIG_CONNECT: true,
  VULTISIG_SLOGAN: true,
  VULTISIG_WEB3: true,
  // W
  // Y
  // Z
});
