// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file coin.proto (package keysign, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coin.proto.
 */
export const file_coin: GenFile = /*@__PURE__*/
  fileDesc("Cgpjb2luLnByb3RvEgdrZXlzaWduIrwBCgRDb2luEg0KBWNoYWluGAEgASgJEg4KBnRpY2tlchgCIAEoCRIPCgdhZGRyZXNzGAMgASgJEhgKEGNvbnRyYWN0X2FkZHJlc3MYBCABKAkSEAoIZGVjaW1hbHMYBSABKAUSGQoRcHJpY2VfcHJvdmlkZXJfaWQYBiABKAkSFwoPaXNfbmF0aXZlX3Rva2VuGAcgASgIEhYKDmhleF9wdWJsaWNfa2V5GAggASgJEgwKBGxvZ28YCSABKAliBnByb3RvMw");

/**
 * Coin only contains information that the app can use it to identify the relevant coin in the vault
 *
 * @generated from message keysign.Coin
 */
export type Coin = Message<"keysign.Coin"> & {
  /**
   * @generated from field: string chain = 1;
   */
  chain: string;

  /**
   * @generated from field: string ticker = 2;
   */
  ticker: string;

  /**
   * @generated from field: string address = 3;
   */
  address: string;

  /**
   * @generated from field: string contract_address = 4;
   */
  contractAddress: string;

  /**
   * @generated from field: int32 decimals = 5;
   */
  decimals: number;

  /**
   * @generated from field: string price_provider_id = 6;
   */
  priceProviderId: string;

  /**
   * @generated from field: bool is_native_token = 7;
   */
  isNativeToken: boolean;

  /**
   * @generated from field: string hex_public_key = 8;
   */
  hexPublicKey: string;

  /**
   * @generated from field: string logo = 9;
   */
  logo: string;
};

/**
 * Describes the message keysign.Coin.
 * Use `create(CoinSchema)` to create a new message.
 */
export const CoinSchema: GenMessage<Coin> = /*@__PURE__*/
  messageDesc(file_coin, 0);

