// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file thorchain_swap_payload.proto (package keysign, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "./coin_pb";
import { file_coin } from "./coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file thorchain_swap_payload.proto.
 */
export const file_thorchain_swap_payload: GenFile = /*@__PURE__*/
  fileDesc("Chx0aG9yY2hhaW5fc3dhcF9wYXlsb2FkLnByb3RvEgdrZXlzaWduIuUCChRUSE9SQ2hhaW5Td2FwUGF5bG9hZBIUCgxmcm9tX2FkZHJlc3MYASABKAkSIAoJZnJvbV9jb2luGAIgASgLMg0ua2V5c2lnbi5Db2luEh4KB3RvX2NvaW4YAyABKAsyDS5rZXlzaWduLkNvaW4SFQoNdmF1bHRfYWRkcmVzcxgEIAEoCRIbCg5yb3V0ZXJfYWRkcmVzcxgFIAEoCUgAiAEBEhMKC2Zyb21fYW1vdW50GAYgASgJEhkKEXRvX2Ftb3VudF9kZWNpbWFsGAcgASgJEhcKD3RvX2Ftb3VudF9saW1pdBgIIAEoCRIaChJzdHJlYW1pbmdfaW50ZXJ2YWwYCSABKAkSGgoSc3RyZWFtaW5nX3F1YW50aXR5GAogASgJEhcKD2V4cGlyYXRpb25fdGltZRgLIAEoBBIUCgxpc19hZmZpbGlhdGUYDCABKAhCEQoPX3JvdXRlcl9hZGRyZXNzYgZwcm90bzM", [file_coin]);

/**
 * @generated from message keysign.THORChainSwapPayload
 */
export type THORChainSwapPayload = Message<"keysign.THORChainSwapPayload"> & {
  /**
   * @generated from field: string from_address = 1;
   */
  fromAddress: string;

  /**
   * @generated from field: keysign.Coin from_coin = 2;
   */
  fromCoin?: Coin;

  /**
   * @generated from field: keysign.Coin to_coin = 3;
   */
  toCoin?: Coin;

  /**
   * @generated from field: string vault_address = 4;
   */
  vaultAddress: string;

  /**
   * @generated from field: optional string router_address = 5;
   */
  routerAddress?: string;

  /**
   * @generated from field: string from_amount = 6;
   */
  fromAmount: string;

  /**
   * @generated from field: string to_amount_decimal = 7;
   */
  toAmountDecimal: string;

  /**
   * @generated from field: string to_amount_limit = 8;
   */
  toAmountLimit: string;

  /**
   * @generated from field: string streaming_interval = 9;
   */
  streamingInterval: string;

  /**
   * @generated from field: string streaming_quantity = 10;
   */
  streamingQuantity: string;

  /**
   * @generated from field: uint64 expiration_time = 11;
   */
  expirationTime: bigint;

  /**
   * @generated from field: bool is_affiliate = 12;
   */
  isAffiliate: boolean;
};

/**
 * Describes the message keysign.THORChainSwapPayload.
 * Use `create(THORChainSwapPayloadSchema)` to create a new message.
 */
export const THORChainSwapPayloadSchema: GenMessage<THORChainSwapPayload> = /*@__PURE__*/
  messageDesc(file_thorchain_swap_payload, 0);

