// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file utxo_info.proto (package keysign, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file utxo_info.proto.
 */
export const file_utxo_info: GenFile = /*@__PURE__*/
  fileDesc("Cg91dHhvX2luZm8ucHJvdG8SB2tleXNpZ24iNwoIVXR4b0luZm8SDAoEaGFzaBgBIAEoCRIOCgZhbW91bnQYAiABKAMSDQoFaW5kZXgYAyABKA1iBnByb3RvMw");

/**
 * @generated from message keysign.UtxoInfo
 */
export type UtxoInfo = Message<"keysign.UtxoInfo"> & {
  /**
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * @generated from field: int64 amount = 2;
   */
  amount: bigint;

  /**
   * @generated from field: uint32 index = 3;
   */
  index: number;
};

/**
 * Describes the message keysign.UtxoInfo.
 * Use `create(UtxoInfoSchema)` to create a new message.
 */
export const UtxoInfoSchema: GenMessage<UtxoInfo> = /*@__PURE__*/
  messageDesc(file_utxo_info, 0);

